language: ruby
rvm:
  - 1.8.7-p374
  - 1.9.3
gemfile:
  - gemfiles/rails_31.gemfile
  - gemfiles/rails_32.gemfile
  - gemfiles/rails_4.gemfile
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4.gemfile
notifications:
  email: false
