language: ruby
sudo: false
cache: bundler
rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.3
gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_41.gemfile
  - gemfiles/rails_42.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_51.gemfile
  - gemfiles/rails_52.gemfile
  - gemfiles/http2.gemfile
  - gemfiles/http3.gemfile
  - gemfiles/http4.gemfile
env:
  - TEST_SUITE=rake

before_install:
  - gem update bundler

script:
  - bundle exec $TEST_SUITE

matrix:
  include:
    - rvm: 2.5.3
      gemfile: gemfiles/rails_5.gemfile
      env: TEST_SUITE="rubocop lib/ spec/"

notifications:
  email: false
